# Generated by Django 5.1.4 on 2024-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=255)),
                ('mark', models.IntegerField()),
                ('negative_mark', models.IntegerField()),
            ],
        ),
    ]
